# Project information
site_name: ONZACK Docs
site_author: ONZACK AG
site_description: >-
  This is only for testing Material for MkDocs.
  Thanks to Squidfunk for this awesome project!

# Repository
repo_url: https://github.com/R-Studio/material-mkdocs-test
repo_name: ONZACK Docs

# Copyright
copyright: Copyright &copy; 2022 Robin Hermann

# Configuration
theme:
  name: null
  custom_dir: mkdocs-material/material

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  logo: assets/logo.png
  favicon: assets/logo.png
  palette: 
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

# Plugins
plugins: 
  - search
  - tags
  - git-revision-date-localized:
      enable_creation_date: true

# Extensions
markdown_extensions:
  - meta

# Customization
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/onzack
      name: ONZACK on GitHub

# CSS customization
extra_css:
  - stylesheets/extra.css