site_name: My Docs
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette: 
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
#plugins: # I think there is a bug (if you enable this plugin, the search bar disappears)
#  - tags
#markdown_extensions:
#  - meta
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://github.com/onzack
      name: ONZACK on GitHub
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/R-Studio/material-mkdocs-test